In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold

import numpy 
import pandas as pd
import tensorflow as tf

# seed 값 설정
seed = 0
numpy.random.seed(3)
tf.random.set_seed(2)

df = pd.read_csv('dataset/sonar.csv', header=None)

dataset = df.values
X = dataset[:,0:60].astype(float)
Y_obj = dataset[:,60]

e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

# 10개의 파일로 쪼갬

n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=3)

# 빈 accuracy 배열
accuracy = []

# 모델의 설정, 컴파일, 실행
for train, test in skf.split(X,Y):
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
    model.fit(X[train], Y[train], epochs=100, batch_size=5)
    k_accuracy = "%.4f" % (model.evaluate(X[test], Y[test])[1])
    accuracy.append(k_accuracy)
    
# 결과 출력
print("\n %.f fold accuracy:" % n_fold, accuracy)

Epoch 1/100
38/38 [==============================] - 0s 934us/step - loss: 0.2558 - accuracy: 0.5294
Epoch 2/100
38/38 [==============================] - 0s 895us/step - loss: 0.2431 - accuracy: 0.5401
Epoch 3/100
38/38 [==============================] - 0s 843us/step - loss: 0.2364 - accuracy: 0.6150
Epoch 4/100
38/38 [==============================] - 0s 869us/step - loss: 0.2269 - accuracy: 0.6471
Epoch 5/100
38/38 [==============================] - 0s 816us/step - loss: 0.2189 - accuracy: 0.7112
Epoch 6/100
38/38 [==============================] - 0s 816us/step - loss: 0.2093 - accuracy: 0.7166
Epoch 7/100
38/38 [==============================] - 0s 763us/step - loss: 0.2046 - accuracy: 0.6898
Epoch 8/100
38/38 [==============================] - 0s 816us/step - loss: 0.1903 - accuracy: 0.7433
Epoch 9/100
38/38 [==============================] - 0s 789us/step - loss: 0.1799 - accuracy: 0.7914
Epoch 10/100
38/38 [==============================] - 0s 684us/step - loss: 0.1699 - accura

In [7]:
print(X[train])

[[0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 [0.01   0.0171 0.0623 ... 0.0044 0.004  0.0117]
 [0.0762 0.0666 0.0481 ... 0.0048 0.0107 0.0094]
 ...
 [0.0323 0.0101 0.0298 ... 0.0032 0.0062 0.0067]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
